const APP_NAME = "HR APP";

const SERVICE_COMPNY_URL = "http://127.0.0.1:81";

const LOREM_IPSUM = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam lobortis elementum egestas. Proin suscipit suscipit tincidunt. Cras iaculis, nibh at laoreet maximus, diam nisl molestie odio, et egestas leo urna ac magna. Fusce tempus lacinia arcu, eget elementum purus varius a. Aenean quis ipsum eleifend, vehicula risus ac, dictum risus. Nam pellentesque quis velit eget sagittis. Praesent commodo nisi a tempor maximus. Donec ex est, fringilla eu interdum at, imperdiet id nibh.
Nulla luctus scelerisque scelerisque.Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Aenean cursus, quam id placerat fermentum, est nulla rhoncus libero, eget mollis nunc purus a augue.Ut dapibus erat a varius eleifend.Duis vestibulum est ac dui faucibus, et scelerisque tellus viverra.Suspendisse viverra, turpis quis fringilla efficitur, risus justo efficitur ligula, id efficitur nunc nunc nec erat.Nam ornare libero tellus, id euismod orci lobortis id.
Mauris lobortis pretium tellus eu fermentum.Aenean eget consequat ex, sit amet suscipit velit.Sed sit amet nisl fringilla, mattis metus in, faucibus tellus.Quisque egestas felis erat, vitae tincidunt lacus bibendum non.Nunc semper mi at nulla laoreet ullamcorper.Phasellus tortor nunc, pretium faucibus augue a, mollis tempus tellus.Aliquam nec nisi nisl.Sed bibendum odio in magna auctor, id hendrerit leo accumsan.Mauris malesuada ligula et condimentum hendrerit.Morbi sed ante dolor.Nam sit amet urna semper, pulvinar sapien et, bibendum nibh.Fusce ac vehicula massa.
Duis lacus risus, scelerisque pellentesque ipsum in, pellentesque ultrices tortor.Quisque pharetra ultricies massa, ac pellentesque odio pellentesque a.Mauris non erat nec est sodales auctor et non risus.Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.Etiam porta, turpis et tincidunt iaculis, eros tellus aliquet tortor, ut finibus turpis mi eu enim.Mauris in tortor est.Vestibulum mattis efficitur magna porttitor consectetur.Nullam non sem vel neque faucibus laoreet.Sed ultricies metus vel vehicula vestibulum.
Mauris viverra turpis at tellus molestie iaculis.Mauris mi enim, convallis et ornare eu, sollicitudin finibus lorem.Phasellus sit amet augue justo.Suspendisse imperdiet mollis sollicitudin.Mauris efficitur ipsum diam, ac luctus odio viverra vitae.Etiam at libero malesuada, bibendum nisi vitae, aliquet mi.Nunc et varius dolor.`;

export { APP_NAME, LOREM_IPSUM, SERVICE_COMPNY_URL };