import File, { FileType, FileKind } from '../types/File';

const generateUUID = () => 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
});


const files: File[] = [
    {
        uuid: generateUUID(),
        type: FileType.DOCUMENT,
        kind: FileKind.AGREEMENT,
        filePath: '/files/agreement_1.pdf',
        originalName: 'Umowa_1.pdf',
        hashedName: 'hashed_agreement_1',
        extension: 'PDF',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: generateUUID(),
        type: FileType.PHOTO,
        kind: FileKind.COMPANY_LOGO,
        filePath: '/files/logo_tech_innovators.png',
        originalName: 'Logo_Tech_Innovators.png',
        hashedName: 'hashed_logo_tech_innovators',
        extension: 'PNG',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: generateUUID(),
        type: FileType.DOCUMENT,
        kind: FileKind.USER_PHOTO,
        filePath: '/files/user_photo_1.jpg',
        originalName: 'User_Photo_1.jpg',
        hashedName: 'hashed_user_photo_1',
        extension: 'JPG',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: generateUUID(),
        type: FileType.DOCUMENT,
        kind: FileKind.REPORT,
        filePath: '/files/report_2024.csv',
        originalName: 'Raport_2024.csv',
        hashedName: 'hashed_report_2024',
        extension: 'CSV',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: generateUUID(),
        type: FileType.PHOTO,
        kind: FileKind.USER_PHOTO,
        filePath: '/files/user_photo_2.png',
        originalName: 'User_Photo_2.png',
        hashedName: 'hashed_user_photo_2',
        extension: 'PNG',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: generateUUID(),
        type: FileType.DOCUMENT,
        kind: FileKind.AGREEMENT,
        filePath: '/files/agreement_2.pdf',
        originalName: 'Umowa_2.pdf',
        hashedName: 'hashed_agreement_2',
        extension: 'PDF',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: generateUUID(),
        type: FileType.PHOTO,
        kind: FileKind.COMPANY_LOGO,
        filePath: '/files/logo_green_solutions.jpg',
        originalName: 'Logo_Green_Solutions.jpg',
        hashedName: 'hashed_logo_green_solutions',
        extension: 'JPG',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: generateUUID(),
        type: FileType.DOCUMENT,
        kind: FileKind.REPORT,
        filePath: '/files/report_2023.xlsx',
        originalName: 'Raport_2023.xlsx',
        hashedName: 'hashed_report_2023',
        extension: 'XLSX',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: generateUUID(),
        type: FileType.AUDIO,
        kind: FileKind.OTHER,
        filePath: '/files/audio_file_1.mp3',
        originalName: 'Audio_File_1.mp3',
        hashedName: 'hashed_audio_file_1',
        extension: 'MP3',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: generateUUID(),
        type: FileType.VIDEO,
        kind: FileKind.OTHER,
        filePath: '/files/video_file_1.mp4',
        originalName: 'Video_File_1.mp4',
        hashedName: 'hashed_video_file_1',
        extension: 'MP4',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
];

export default files;
