import Position from '../types/Position';

const positions: Position[] = [
    {
        uuid: '1',
        name: 'Manager',
        description: 'Oversees team operations and ensures project goals are met.',
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deletedAt: null,
    },
    {
        uuid: '2',
        name: 'Sales Representative',
        description: 'Manages client relationships and drives sales.',
        active: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deletedAt: null,
    },
    {
        uuid: '3',
        name: 'Software Engineer',
        description: 'Develops and maintains software applications.',
        active: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deletedAt: null,
    },
    {
        uuid: '4',
        name: 'Human Resources Specialist',
        description: 'Handles recruitment, onboarding, and employee relations.',
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deletedAt: null,
    },
    {
        uuid: '5',
        name: 'Marketing Coordinator',
        description: 'Coordinates marketing activities and campaigns.',
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deletedAt: null,
    },
    {
        uuid: '6',
        name: 'Financial Analyst',
        description: 'Analyzes financial data and assists with budgeting.',
        active: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deletedAt: null,
    },
    {
        uuid: '7',
        name: 'Customer Support Specialist',
        description: 'Provides assistance to customers and resolves inquiries.',
        active: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deletedAt: null,
    },
    {
        uuid: '8',
        name: 'Product Manager',
        description: 'Leads product development and coordinates cross-functional teams.',
        active: false,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deletedAt: null,
    },
    {
        uuid: '9',
        name: 'Content Writer',
        description: 'Creates written content for marketing and communication.',
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deletedAt: null,
    },
    {
        uuid: '10',
        name: 'Operations Director',
        description: 'Oversees operational processes and improves efficiency.',
        active: true,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        deletedAt: null,
    }
];

export default positions;
