import Industry from '../types/Industry';

const industries: Industry[] = [
    {
        uuid: '1',
        name: 'Technology',
        description: 'Industry focused on information technology.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: '2',
        name: 'Healthcare',
        description: 'Industry related to healthcare and medicine.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: '3',
        name: 'Education',
        description: 'Industry focused on teaching and education.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: '4',
        name: 'Finance',
        description: 'Industry focused on finance and accounting.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: '5',
        name: 'Transportation',
        description: 'Industry focused on transport and logistics.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: '6',
        name: 'Real Estate',
        description: 'Industry focused on real estate transactions.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: '7',
        name: 'Manufacturing',
        description: 'Industry focused on goods production.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: '8',
        name: 'Services',
        description: 'Industry focused on service provision.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: '9',
        name: 'Media',
        description: 'Industry focused on media and communication.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
    {
        uuid: '10',
        name: 'Agriculture',
        description: 'Industry focused on agricultural production.',
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        deleted_at: null,
    },
];

export default industries;