import type { Metadata } from "next";
import localFont from "next/font/local";
import "./public/globals.css";
import Navigaton from './components/layout/Navigation';
import Content from "./components/layout/Content";
import Footer from "./components/layout/Footer";
import { UserProvider } from './context/UserContext';

const geistSans = localFont({
  src: "./public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "HR App",
  description: "Generated by HR App",
};

const RootLayout = ({ children, }: Readonly<{children: React.ReactNode;}>) => {
  return (
    <html lang="en">   
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProvider>  
          <Navigaton />
          <Content children={children} />
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}

export default RootLayout;
